version: '3.8'
services:
  bunchofllamas:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    env_file:
      - ../.env # Adjust the path to your .env file as needed
    environment:
      MODULE_NAME: "main"
      VARIABLE_NAME: "app"
      PORT: "80"
    command: sh -c "uvicorn $$MODULE_NAME:$$VARIABLE_NAME --host 0.0.0.0 --port $$PORT"
    restart: unless-stopped
    container_name: bunchofllamas
    volumes:
      - .:/backend
